# before_script:
#   - apt-get update -qq
#   - apt-get install -qq git
#   # Setup SSH deploy keys
#   - "which ssh-agent || ( apt-get install -qq openssh-client -y)"
#   - eval $(ssh-agent -s)
#   - ssh-add <(echo "$SSH_PRIVATE_KEY")
#   - mkdir -p ~/.ssh
#   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:          # List of stages for jobs, and their order of execution
  - mirror

variables:
  SA_PASSWORD: $GITHUB_TOKEN
mirror-job:       # This job runs in the build stage, which runs first.
  stage: mirror
  script:

     
    - mkdir temp-dir 
    - env
    - git clone  $CI_REPOSITORY_URL temp-dir
    - cd temp-dir
    - git branch -a
    - git fetch --all
    - git remote rm origin
    - echo $TOKEN
    - ls
    # - git config user.name "LogitSocial"
    # - git config user.email "yadavajeetak47@gmail.com"
    # - git config user.token $TOKEN
    - git config -l
   
    # - git remote add origin https://$TOKEN@github.com/LogitSocial/mirror-poc.git
    - git push -f https://LogitSocial:$SA_PASSWORD@github.com/LogitSocial/mirror-poc.git --all
    # - git push -f https://github.com/LogitSocial/mirror-poc.git --all




