stages:          # List of stages for jobs, and their order of execution
  - mirror


mirror-job:       # This job runs in the build stage, which runs first.
  stage: mirror
  script:

     
    - mkdir temp-dir 
    - env
    - git clone  $CI_REPOSITORY_URL temp-dir
    - cd temp-dir
    - git branch -a
    - git fetch --all
    - git remote rm origin
    - echo $TOKEN
    - ls
    # - git config user.name "LogitSocial"
    # - git config user.email "yadavajeetak47@gmail.com"
    # - git config user.token $TOKEN
    - git config -l
   
    # - git remote add origin https://$TOKEN@github.com/LogitSocial/mirror-poc.git
    - git push -f https://LogitSocial:"$GITHUB_TOKEN"@github.com/LogitSocial/mirror-poc.git --all




