before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - "which ssh-agent || ( apt-get install -qq openssh-client -y)"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d | tr -d "\r" ) 
  # - ssh-add <(echo "$SSH_PRIVATE_KEY_BASE64" ) 
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
 

stages:          # List of stages for jobs, and their order of execution
  - mirror

variables:
  SA_PASSWORD: $GITHUB_TOKEN
mirror-job:       # This job runs in the build stage, which runs first.
  stage: mirror
  script:

     
    - mkdir temp-dir 
    - env
    - git clone  $CI_REPOSITORY_URL temp-dir
    - cd temp-dir
    - git branch -a
    - git fetch --all
    - git remote rm origin
  
    # - git remote add origin https://$TOKEN@github.com/LogitSocial/mirror-poc.git
    # - git push -f https://LogitSocial:$SA_PASSWORD@github.com/LogitSocial/mirror-poc.git --all
    - git push -f git@github.com:LogitSocial/mirror-poc.git --all




